namespace swifty.Code.Syntaxt {
    public enum SyntaxKind {
        // Tokens
        NumberToken,
        CharToken,
        WhitespaceToken,
        CommentToken,
        PlusToken,
        MinusToken,
        StarToken,
        DivideToken,
        EqualToken,
        NotEqualToken,
        NotToken,
        LogicalAndToken,
        LogicalOrToken,
        AssignmentToken,
        TypeCastToken,
        XorToken,
        AndToken,
        OrToken,
        LessThanToken,
        LessThanEqualToken,
        GreaterThanToken,
        GreaterThanEqualToken,
        LeftParanthesisToken,
        RightParanthesisToken,
        OpenBraceToken,
        CloseBraceToken,
        EndofFileToken,
        IdentifierToken,
        BadToken,
        BitwiseNegationToken,
        // Keywords
        TrueKeyword,
        FalseKeyword,
        IntKeyword,
        CharKeyword,
        BoolKeyword,
        ConstKeyword,
        IfKeyword,
        ElseKeyword,
        WhileKeyword,
        ForKeyword,
        ToKeyword,
        KeywordToken, // default error token when a keyword is missing
        // Nodes
        CompilationUnit,
        // Statements
        BlockStatement,
        ExpressionStatement,
        VariableDeclarationStatement,
        IfStatementSyntax,
        ElseClauseSyntax,
        WhileStatementSyntax,
        ForStatementSyntax,
        // Expressions
        LiteralExpression,
        BinaryExpression,
        ParathesisExpression,
        UnaryExpression,
        NameExpression,
        AssignmentExpression,
        TypeCastExpression,
    }
}